apiVersion: openportal.dev/v1alpha1
kind: CloudflareDNSRecord
metadata:
  annotations:
    terasky.backstage.io/source-info: >-
      {"pushToGit":true,"gitBranch":"main","gitRepo":"github.com?owner=open-service-portal&repo=catalog-orders","gitLayout":"cluster-scoped","basePath":"rancher-desktop/demo-cf/CloudflareDNSRecord"}
    terasky.backstage.io/add-to-catalog: 'true'
    terasky.backstage.io/owner: group:default/platform-team
    terasky.backstage.io/system: demo-cf
    terasky.backstage.io/source-file-url: >-
      https://github.com/open-service-portal/catalog-orders/blob/main/rancher-desktop/demo-cf/CloudflareDNSRecord/demo-cf.yaml
  name: demo-cf
  namespace: demo-cf
spec:
  proxied: false
  comment: test
  name: demo-cf
  type: A
  value: 1.1.1.1
