#!/bin/bash
#
# generate-kustomizations.sh - Generate kustomization.yaml for each cluster directory
#
# This script creates a kustomization.yaml file in each cluster directory
# that lists all YAML resources in that directory (recursively).

set -e

# Function to generate kustomization.yaml for a directory
generate_kustomization() {
  local dir="$1"
  local kustomization_file="$dir/kustomization.yaml"
  
  echo "Processing directory: $dir"
  
  # Find all YAML files recursively, excluding kustomization.yaml itself
  yaml_files=()
  while IFS= read -r -d '' file; do
    yaml_files+=("$file")
  done < <(find "$dir" -type f \( -name "*.yaml" -o -name "*.yml" \) ! -name "kustomization.yaml" -print0 2>/dev/null | sort -z)
  
  if [ ${#yaml_files[@]} -eq 0 ]; then
    echo "  No YAML files found in $dir, skipping..."
    return
  fi
  
  # Start creating the kustomization.yaml
  cat > "$kustomization_file" << 'EOF'
# Auto-generated by generate-kustomizations.sh - Do not edit manually
# This file is automatically updated when YAML resources change
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
EOF
  
  # Add each YAML file as a resource (relative to the cluster directory)
  for file in "${yaml_files[@]}"; do
    # Get relative path from the cluster directory
    relative_path="${file#$dir/}"
    echo "  - $relative_path" >> "$kustomization_file"
  done
  
  echo "  ✅ Generated $kustomization_file with ${#yaml_files[@]} resources"
}

# Main execution
echo "🔄 Generating kustomization.yaml files for all cluster directories..."
echo ""

# Process each cluster directory
for cluster_dir in */; do
  # Skip hidden directories, scripts, and .github
  if [[ "$cluster_dir" == .* ]] || [[ "$cluster_dir" == "scripts/" ]] || [[ "$cluster_dir" == ".github/" ]]; then
    continue
  fi
  
  # Remove trailing slash
  cluster_dir="${cluster_dir%/}"
  
  # Only process if it's a directory and not a symlink
  if [ -d "$cluster_dir" ] && [ ! -L "$cluster_dir" ]; then
    generate_kustomization "$cluster_dir"
  fi
done

echo ""
echo "✨ Done! Kustomization files have been generated."
echo ""
echo "You can verify the generated files with:"
echo "  kubectl kustomize <cluster-directory>"